name: qg
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python=3.12
  - pytorch
  - pytorch-cuda=12.4
  - torchaudio
  - torchvision
  - datasets
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - peft
  - transformers
  - seaborn
  - torch-geometric
  - absl-py
  - nltk
  - rouge-score
  - openai
